### ISSUE TITLE
YouTube API change for Vevo video

### ISSUE THREAD

**Issue by hotuy** [0xced/XCDYouTubeKit#198] opened 2015-11-10 16:23 UTC
Several day ago i can play Vevo video, but today all vevo video not played. :(

**Comment by ditimtriky** [comment] 2015-11-10 16:37
Yes, me too. I have to submit tomorrow. It's my deadline :(
Please update asap!
Thanks so much

```[XCDYouTubeKit] Video operation finished with error: This video contains content from **VEVO**. It is restricted from playback on certain sites. Watch on YouTube
Domain: XCDYouTubeVideoErrorDomain
Code:   150
User Info: {
    NSLocalizedDescription = "This video contains content from VEVO. It is restricted from playback on certain sites. Watch on YouTube";
    NSURL = "https://www.youtube.com/get_video_info?el=embedded&hl=en&ps=default&video_id=bs8wzYd3wRo";
}```

```[XCDYouTubeKit] Video operation finished with error: This video contains content from **SME**. It is restricted from playback on certain sites. Watch on YouTube
Domain: XCDYouTubeVideoErrorDomain
Code:   150
User Info: {
    NSLocalizedDescription = "This video contains content from SME. It is restricted from playback on certain sites. Watch on YouTube";
    NSURL = "https://www.youtube.com/get_video_info?el=embedded&hl=en&ps=default&video_id=ojb59AKmybw";
}```

**Comment by 0xABC** [comment] 2015-11-10 20:40
+1
Current release of youtube-dl works (2015.11.10)

**Comment by 0xABC** [comment] 2015-11-10 23:14
Perhaps this is the same as issue #194

**Comment by Pranoy1c** [comment] 2015-11-11 00:00
do we know exactly what changes cause this to break? is there something we can somehow make our apps change on the fly (like if it's just a string which needs to change etc) via a backend server so we don't need to update the apps everytime youtube changes their api?

**Comment by kiwi07** [comment] 2015-11-11 01:45
Hi,
I am facing the same problem. Please tell me how to fix this?
Thanks

**Comment by jeroenransijn** [comment] 2015-11-11 04:38
What about this error? Wondering if it is because of the same thing.
```
Video operation finished with error: This video contains content from UMG. It is restricted from playback on certain sites. Watch on YouTube
Domain: XCDYouTubeVideoErrorDomain
Code:   150
User Info: {
    NSLocalizedDescription = "This video contains content from UMG. It is restricted from playback on certain sites. Watch on YouTube";
    NSURL = "https://www.youtube.com/get_video_info?el=embedded&hl=en&ps=default&video_id=Nt1-PBgh6Vo";
}
```

**Comment by nguyenmanh92** [comment] 2015-11-11 16:09
me too

**Comment by juliorimo** [comment] 2015-11-11 20:35
+1. Please update :(

**Comment by ditimtriky** [comment] 2015-11-12 15:13
I thought that youtube made a new-big-change for its api. We have to find out another solution :(

**Comment by nokai** [comment] 2015-11-12 16:20
+2. Please update .. waiting.. 

Thanks

**Comment by SepiaApps** [comment] 2015-11-12 19:53
+1

**Comment by 0xced** [comment] 2015-11-12 21:03
This issue is actually a duplicate of #193.

**Closed** 2015-11-12 21:04 UTC
Labels: duplicate

**Comment by 0xced** [comment] 2015-11-12 22:14
@Pranoy1c I plan to implement the feature you describe, see #199.

**Comment by tommybananas** [comment] 2016-02-16 00:12
@0xced Could you give us an idea of the kinds of api changes and fixes that typically happen so we can help with a fix? Correct me if I'm wrong but #199 might help with defining the regex, etc endpoint but we still need to implement the actual dynamic injection for those fixes.

**Comment by Pranoy1c** [comment] 2016-02-16 05:42
@tommybananas I agree with you, I was looking for that too. Maybe somehow we can make changes to variables on the fly via our own backend so we don't need to update the app everytime.

**Comment by tommybananas** [comment] 2016-02-16 05:55
@Pranoy1c Yea that seems like the best solution right now, I was just looking for any tips before I try to wade through every commit. In another thread I believe @0xced mentioned it wasn't ALL api params, but I could be mistaken.
