### ISSUE TITLE
Error - "This video contains content from WMG"

### ISSUE THREAD

**Issue by yoasha** [0xced/XCDYouTubeKit#202] opened 2015-11-11 18:34 UTC
This issue may already been reported, but I couldn't find it in the issue list.

Here is the error:

User Info: {
    NSLocalizedDescription = "This video contains content from WMG. It is restricted from playback on certain sites. Watch on YouTube";
    NSURL = "https://www.youtube.com/get_video_info?el=embedded&hl=en&ps=default&video_id=Bs8AXlTwhJ0";
}

Some video_ids with this issue:
Bs8AXlTwhJ0
_gHZ2eoOk-I
s6Df-f45MJg
vggrVbt5L30
NkyL1HSNufA
6gQh_mEK_8g
FaOBOGA_PJ0
JOUEfB7u4_4
JQFufHNwIPA

**Comment by jeroenransijn** [comment] 2015-11-12 00:16
Possibly related to #198

**Comment by 0xced** [comment] 2015-11-12 21:04
This issue is actually a duplicate of #193.

**Closed** 2015-11-12 21:04 UTC
Labels: duplicate
