### ISSUE TITLE
Play the last played video from the stop time.

### ISSUE THREAD

**Issue by akash-mastercreationz** [0xced/XCDYouTubeKit#326] opened 2017-03-18 06:07 UTC
Is there any way to save the songs played and whenever user play the same song, the song will start from the time it was stopped. Like in youtube .

**Comment by SoneeJohn** [comment] 2017-03-24 01:14
@akash-mastercreationz you will need to save the time of the video (if you're using `AVPlayer`you can use `-currentTime` [method](https://developer.apple.com/reference/avfoundation/avplayer/1390404-currenttime?language=objc). Once you've saved this data somewhere maybe in an `NSMutableDictionary` when the user plays the video, again assuming that you're using `AVPlayer` use the `-seek​To​Time:` instance [method](https://developer.apple.com/reference/avfoundation/avplayer/1385953-seektotime?language=objc). Note, that you can only all this method if the`AVPlayer` status is equal to [`AVPlayer​Item​Status​Ready​To​Play`](https://developer.apple.com/reference/avfoundation/avplayeritemstatus?language=objc)

**Comment by SoneeJohn** [comment] 2017-03-24 01:22
@akash-mastercreationz here is a code snippet on how to use the seeking.

```objc
switch (self.playerView.player.currentItem.status) {
       case AVPlayerItemStatusReadyToPlay:
         [self.playerView.player seekToTime:CMTimeMake(50, 1.0) completionHandler:^(BOOL finished) {
                  [self.playerView.player play];
           }];
}
```

**Comment by SoneeJohn** [comment] 2017-03-24 01:40
@akash-mastercreationz you will probably want to use KVO and observe the changes of the `AVPlayerItem`'s status.

**Comment by 0xced** [comment] 2017-04-07 10:10
Closing this as a duplicate of #327.

**Closed by 0xced** 2017-04-07 10:10 UTC
