### ISSUE TITLE
Vevo video error 

### ISSUE THREAD

**Issue by lacyleo** [0xced/XCDYouTubeKit#152] opened 2015-06-12 02:22 UTC
Error while getting youtube stream:Error Domain=XCDYouTubeVideoErrorDomain Code=150 "This video contains content from VEVO. It is restricted from playback on certain sites. Watch on YouTube" UserInfo=0x1706791c0 {NSURL=https://www.youtube.com/get_video_info?el=embedded&hl=en&ps=default&video_id=wQfP1lcJ_eo, NSLocalizedDescription=This video contains content from VEVO. It is restricted from playback on certain sites. Watch on YouTube}

Any help?

**Comment by 0xced** [comment] 2015-06-14 21:41
Are you using the latest version of XCDYouTubeKit, i.e. 2.1.3? The video `wQfP1lcJ_eo` (Florida Georgia Line - Anything Goes) plays fine for me.

**Comment by conanm** [comment] 2015-06-17 14:49
i think this might happen if you load the same video from the same IP a few times in a row.  occurred during testing where i loaded the same VEVO track around 6 times in quick succession (was doing some pixel pushing in simulator)

**Comment by 0xced** [comment] 2015-06-24 19:16
I just tried to load the same VEVO video about 20 times in a row but I could not reproduce the problem. Now that version 2.2.0 supports [logging](https://github.com/0xced/XCDYouTubeKit/blob/2.2.0/README.md#logging), I suggest you to set the `XCDYouTubeKitLogLevel` environment variable to `0x1F` to log almost everything. If you can reproduce the problem, the logs may explain what’s happening.

**Comment by 0xced** [comment] 2015-07-16 00:56
No reply from OP for one month, so I’m closing the issue.

**Closed by 0xced** 2015-07-16 00:56 UTC
Labels: waiting for reply

**Comment by kungfoolabs** [comment] 2016-02-27 07:17
So strange. this happens to me too. But if I create a new app, it works fine.

**Comment by kungfoolabs** [comment] 2016-02-27 09:27
nvm. it's cause of 2.5 -> 2.51
