### ISSUE TITLE
problem on vevo videos

### ISSUE THREAD

**Issue by codaman** [0xced/XCDYouTubeKit#144] opened 2015-05-13 08:38 UTC
vevo videos no longer opening

**Comment by imclean** [comment] 2015-05-13 11:14
I'll second that..

**Comment by nokai** [comment] 2015-05-13 11:56
also do not work SME Videos

**Comment by codaman** [comment] 2015-05-13 12:15
i've tried many different solution but i haven't succeed

**Comment by Quapper** [comment] 2015-05-13 12:21
Yep, broken again for all kinds of videos like this.

**Comment by codaman** [comment] 2015-05-13 14:55
i've looked some apps continue to work. there must be an another technique

**Comment by psycotica0** [comment] 2015-05-13 15:00
@0xced Are you looking at this right now? I'll need to start looking into it in the next couple hours, but if you're already working on it, there's no sense in both of us doing it.

If you're busy, though, it'd be good for me to not expect an upstream fix soon.

**Comment by 0xced** [comment] 2015-05-13 16:04
I already started to look into it. The problem is that the execution of the player JavaScript fails with `TypeError: undefined is not an object (evaluating 'window.navigator.j')` before it can evaluate the parts required to descramble the signature. I’m not sure yet what is the most sustainable solution.

**Comment by psycotica0** [comment] 2015-05-13 16:08
Cool. YouTube DL seems to be working without change, so something fundamental isn't different. Which is nice.

**Comment by sycode** [comment] 2015-05-13 18:39
### Signature function (Javascript)

```javascript
function it(a) {
    a = a.split("");
    ht.De(a, 14);
    ht.po(a, 54);
    ht.PF(a, 1);
    ht.De(a, 37);
    ht.De(a, 61);
    ht.po(a, 68);
    return a.join("")
}
```

### unscrambleSignature function (Objective-C)
```
JSValueRef unscrambledSignatureValue = JSObjectCallAsFunction(self.context, self.signatureFunction, NULL, 1, &scrambledSignatureValue, &exception);
```

### exception
```
TypeError: undefined is not an object (evaluating 'ht.De')
```

Is it the reference error to the internal function?

**Comment by psycotica0** [comment] 2015-05-13 22:48
I read through the JS, and `ht.De(a, n)` works out to "swap the nth and 0th characters of a", `ht.po(a, n)` works out to "reverse a, ignore n", and `ht.PF(a, n)` works out to "drop n characters off the front of a"

So it just scrambles it a little.
If I just translate that function as the body of the `unscrambleSignature:`, it mostly works.
One test legitimately fails, and another fails because it tests a broken signature function.

The issue is, I don't know how often that little script changes.
YoutubeDL also parses out and reads this function, but it does it using some terrible regular expressions and a switch statement as a really sketchy parser / tokenizer / interpreter.

On the other hand, it's working right now...

That's why they aren't having these issues.

**Comment by psycotica0** [comment] 2015-05-13 22:51
I feel like it'd be nice if the JS issues were resolved, and this thing that had been working kept working.
If there's no fix by tomorrow, I'll try. Something.

**Comment by 0xced** [comment] 2015-05-13 22:55
As you noticed, youtube-dl has its own [JavaScript interpreter](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/jsinterp.py), or rather a narrow subset of JavaScript. With JavaScriptCore available on iOS and OS X, there is no way I’m going down that route.

I have found a solution and I’m currently polishing it. I hope to make it available soon.

**Comment by 0xced** [comment] 2015-05-14 07:58
I just pushed a fix on the `develop` branch, please test if everything is OK. I will try to publish version 2.1.3 tonight (CEST).

**Comment by codaman** [comment] 2015-05-14 08:11
very thnx @0xced @psycotica0

**Comment by neen1** [comment] 2015-05-14 08:29
working now thx @0xced  @psycotica0

**Comment by Quapper** [comment] 2015-05-14 08:34
Works for me :) Thanks for the great work you do.

**Comment by sycode** [comment] 2015-05-14 08:38
It was working.
Very thanks.

**Comment by psycotica0** [comment] 2015-05-14 14:37
Looks good from here. Thanks!

**Closed** 2015-05-15 10:16 UTC
Labels: bug
