### ISSUE TITLE
Restricted Access!

### ISSUE THREAD

**Issue by omose14** [0xced/XCDYouTubeKit#259] opened 2016-06-24 02:28 UTC
It will now longer let you play some video like VEVO video or UMG etc

**Comment by mzgaljic** [comment] 2016-06-24 02:31
Did you look at issue #257??? I have a hunch this is the same problem, which has already been resolved (temporarily) by someone else.

**Comment by 0xced** [comment] 2016-06-24 07:05
Indeed, this is a duplicate of #257.

**Closed by 0xced** 2016-06-24 07:05 UTC
