### ISSUE TITLE
Can't play certain videos

### ISSUE THREAD

**Issue by jeroenransijn** [0xced/XCDYouTubeKit#196] opened 2015-11-10 07:46 UTC
I am using XCDYouTubeKit to create a YouTube player. There is a search functionality to retrieve results from the YouTube Data Api V3. Some videos load, and others don't.

One of the errors I got is this:
```
Video operation finished with error: The operation couldn’t be completed. (XCDYouTubeVideoErrorDomain error -2.)
Domain: XCDYouTubeVideoErrorDomain
Code:   -2
User Info: {
    NSURL = "https://www.youtube.com/get_video_info?el=detailpage&hl=en&ps=default&video_id=xDufK_LVzgE";
}
```

How do I know what videos will work?

**Comment by ostapkuzyk** [comment] 2015-11-10 16:59
Have the same issue. And in log I can see:
JavaScript exception: TypeError: undefined is not an object (evaluating 'window.location.hash')

**Comment by peterpaulis** [comment] 2015-11-10 18:29
Same problem

Error Domain=XCDYouTubeVideoErrorDomain Code=-2 "(null)" UserInfo={NSURL=https://www.youtube.com/get_video_info?el=detailpage&hl=en&ps=default&video_id=7jTyvm27EsE}

**Comment by jeroenransijn** [comment] 2015-11-11 04:35
I am wondering what gives us this error. A bug in XCDYouTubeKit, or YouTube is blocking us?

**Comment by tamnv110** [comment] 2015-11-12 03:29
I also encountered this error. Please fix bug.

**Comment by 0xced** [comment] 2015-11-12 21:03
This issue is actually a duplicate of #193.

**Closed** 2015-11-12 21:03 UTC
Labels: duplicate
