### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by evgenijromanishyn** [0xced/XCDYouTubeKit#143] opened 2015-05-13 08:36 UTC
Not work with video id 4YqV8n_kfsU

**Comment by codaman** [comment] 2015-05-13 08:39
vevo videos no longer opening

**Comment by evgenijromanishyn** [comment] 2015-05-13 08:48
Yesterday worked ...

**Comment by codaman** [comment] 2015-05-13 08:50
something again changed in youtube api

**Comment by codaman** [comment] 2015-05-13 08:51
i'm trying old version of xcd

**Comment by evgenijromanishyn** [comment] 2015-05-13 08:54
Can you fix it?

**Comment by codaman** [comment] 2015-05-13 08:56
unfortunately :(

**Comment by evgenijromanishyn** [comment] 2015-05-13 08:59
You can download the video at this link:
https://www.SSyoutube.com/watch?v=4YqV8n_kfsU

Just add the "ss" letters.
How do they do it?

**Comment by codaman** [comment] 2015-05-13 09:12
fetching video url much simpler on browser for example open video on chrome and open page source you can easily get video url

**Comment by evgenijromanishyn** [comment] 2015-05-13 09:16
A very simple example :-)

- (void)loadDirectLink
{   
    NSString *url = [NSString stringWithFormat:@"https://www.ssyoutube.com/watch?v=%@", self.videoIdentifier];
    NSURL *validURL = [NSURL URLWithString:url];
    self.webView = [[UIWebView alloc] initWithFrame:CGRectZero];
    [self.webView loadRequest:[ NSURLRequest requestWithURL:validURL]];
    self.webView.delegate = self;
    self.webView.mediaPlaybackRequiresUserAction = NO;
}

- (void)webViewDidFinishLoad:(UIWebView *)webView
{
    NSString *html = [webView stringByEvaluatingJavaScriptFromString:@"document.body.innerHTML"];
    if ([html containsString:@"MP4"]) {
        if ([html containsString:@"link-download"]) {
            NSArray *links = [html componentsSeparatedByString:@"link-download"];
            for (NSString *link in links) {
                if ([link.lowercaseString containsString:@"mp4"]) {
                    NSString *validURL = [self validVideoURL:link];
                    if (validURL.length) {
                        self.url = [NSURL URLWithString:validURL];
                        [self startVideo];
                    }
                }
            }
        }
    }
}

**Comment by codaman** [comment] 2015-05-13 10:46
this technique is not working

**Comment by codaman** [comment] 2015-05-13 10:46
have u tried this

**Comment by codaman** [comment] 2015-05-13 13:07
- (NSString *) unscrambleSignature:(NSString *)scrambledSignature this method returns nil. I don't know how is it work

**Comment by 0xced** [comment] 2015-05-13 14:55
Duplicate of #144.

**Closed by 0xced** 2015-05-13 14:55 UTC
