### ISSUE TITLE
XCode 7 ld -U error

### ISSUE THREAD

**Issue by donpark** [0xced/XCDYouTubeKit#175] opened 2015-09-16 23:48 UTC
XCode 7 build failed with following error:

    ld: -U and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together

Only place where -U LDFLAGS is used is in XCDYouTubeKit:

    -U,_JSContextGetGlobalObject -Wl,-U,_JSEvaluateScript -Wl,-U,_JSGlobalContextCreate -Wl,-U,_JSGlobalContextRelease -Wl,-U,_JSObjectCallAsFunction -Wl,-U,_JSObjectIsFunction -Wl,-U,_JSObjectMake -Wl,-U,_JSObjectSetProperty -Wl,-U,_JSStringCopyCFString -Wl,-U,_JSStringCreateWithCFString -Wl,-U,_JSStringRelease -Wl,-U,_JSValueIsObject -Wl,-U,_JSValueIsString -Wl,-U,_JSValueMakeString -Wl,-U,_JSValueToStringCopy

WORKAROUND: Disable bitcode which is AFAIK required only for Apple Watch.

**Comment by 0xced** [comment] 2015-09-17 15:06
This is a duplicate of #173. Please upgrade to XCDYouTubeKit 2.3.0 which solves this issue.

**Closed by 0xced** 2015-09-17 15:06 UTC
Labels: duplicate

**Comment by donpark** [comment] 2015-09-18 00:41
awesome. thx.
