### ISSUE TITLE
Vevo type error while getting stream.

### ISSUE THREAD

**Issue by lacyleo** [0xced/XCDYouTubeKit#194] opened 2015-11-10 03:25 UTC
Video id:YQHsXMglC9A
Here's log: 
User Info: {
    NSLocalizedDescription = "This video contains content from VEVO. It is restricted from playback on certain sites. Watch on YouTube";
    NSURL = "https://www.youtube.com/get_video_info?el=embedded&hl=en&ps=default&video_id=YQHsXMglC9A";
}

**Comment by abingeorgev** [comment] 2015-11-10 05:56
Same here. It was playing yesterday. But today, its not working.

**Comment by juliorimo** [comment] 2015-11-11 20:33
+1

**Comment by 0xced** [comment] 2015-11-12 21:01
This issue is actually a duplicate of #193.

**Closed by 0xced** 2015-11-12 21:01 UTC
Labels: bug
