### ISSUE TITLE
XCDYouTubeKit-master/XCDYouTubeKit/XCDYouTubeVideoOperation.m:112:57: 'initWithRequest:delegate:startImmediately:' is deprecated: first deprecated in iOS 9.0 - Use NSURLSession (see NSURLSession.h)

### ISSUE THREAD

**Issue by SatyanarayanaKV** [0xced/XCDYouTubeKit#210] opened 2015-11-18 09:59 UTC
Need help..

**Comment by SoneeJohn** [comment] 2015-11-20 20:19
@SatyanarayanaKV NSURLConnection is deprecated however, it will still work on OS X 10.11 and iOS 9. The author of the library is currently working to migrate XCDYouTubeKit to NSURLSession. You can view this branch:
https://github.com/0xced/XCDYouTubeKit/tree/NSURLSession-diagnostic

**Comment by 0xced** [comment] 2015-11-24 20:07
This is a duplicate of #190 and it will be addressed in the next release.

**Closed by 0xced** 2015-11-24 20:07 UTC
Labels: duplicate
